{
 "title": "ShieldAPI System Performance",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Throughput (Requests per Minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count[1m])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Average Request Latency (seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum[1m])) by (application) / sum(rate(http_server_requests_seconds_count[1m])) by (application)",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Detected Threats (Rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(shieldapi_threats_detected_total[1m])) by (category)",
     "legendFormat": "{{category}}"
    }
   ]
  },
  {
   "title": "Blocked Requests (Rate per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(shieldapi_requests_blocked_total[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}