services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SHIELDAPI_LOGGING_LOGSTASH_DESTINATION=${LOGSTASH_SERVER}
    env_file: .env

  auth-service:
    build: ./auth-service
    ports:
      - "8084:8084"
    environment:
      - SHIELDAPI_LOGGING_LOGSTASH_DESTINATION=${LOGSTASH_SERVER}
    env_file: .env
    depends_on:
      - discovery-server
      - postgres

  security-service:
    build: ./security-service
    ports:
      - "8081:8081"
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAFKA_SERVER=${KAFKA_SERVER}
      - REDIS_HOST=${REDIS_HOST}
      - SHIELDAPI_LOGGING_LOGSTASH_DESTINATION=${LOGSTASH_SERVER}
    env_file: .env
    depends_on:
      - discovery-server
      - postgres
      - kafka
      - redis

  analytics-service:
    build: ./analytics-service
    ports:
      - "8082:8082"
    environment:
      - EUREKA_SERVER=${EUREKA_SERVER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - KAFKA_SERVER=${KAFKA_SERVER}
      - REDIS_HOST=${REDIS_HOST}
      - SHIELDAPI_LOGGING_LOGSTASH_DESTINATION=${LOGSTASH_SERVER}
    env_file: .env
    depends_on:
      - discovery-server
      - postgres
      - kafka
      - redis

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    environment:
      - SHIELDAPI_LOGGING_LOGSTASH_DESTINATION=${LOGSTASH_SERVER}
    env_file: .env
    depends_on:
      - discovery-server
      - kafka

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    environment:
      - SHIELDAPI_LOGGING_LOGSTASH_DESTINATION=${LOGSTASH_SERVER}
    env_file: .env
    depends_on:
      - discovery-server
      - auth-service
      - security-service
      - analytics-service
      - kafka
      - redis

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - gateway-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.10
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
